/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Affirmation {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
  'isCustom' : boolean,
  'category' : Category,
  'authorPrincipal' : Principal,
}
export interface AffirmationWithFavorite {
  'affirmation' : Affirmation,
  'isFavorite' : boolean,
}
export type Category = { 'gratitude' : null } |
  { 'love' : null } |
  { 'mindfulness' : null } |
  { 'success' : null } |
  { 'confidence' : null } |
  { 'health' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'create' : ActorMethod<[string, Category], bigint>,
  'delete' : ActorMethod<[bigint], undefined>,
  'getAllByCategory' : ActorMethod<[Category], Array<AffirmationWithFavorite>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomAffirmations' : ActorMethod<[], Array<AffirmationWithFavorite>>,
  'getDailyAffirmation' : ActorMethod<[], AffirmationWithFavorite>,
  'getFavorites' : ActorMethod<[], Array<AffirmationWithFavorite>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleFavorite' : ActorMethod<[bigint], undefined>,
  'update' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];