/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'gratitude' : IDL.Null,
  'love' : IDL.Null,
  'mindfulness' : IDL.Null,
  'success' : IDL.Null,
  'confidence' : IDL.Null,
  'health' : IDL.Null,
});
export const Time = IDL.Int;
export const Affirmation = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'isCustom' : IDL.Bool,
  'category' : Category,
  'authorPrincipal' : IDL.Principal,
});
export const AffirmationWithFavorite = IDL.Record({
  'affirmation' : Affirmation,
  'isFavorite' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'create' : IDL.Func([IDL.Text, Category], [IDL.Nat], []),
  'delete' : IDL.Func([IDL.Nat], [], []),
  'getAllByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(AffirmationWithFavorite)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomAffirmations' : IDL.Func(
      [],
      [IDL.Vec(AffirmationWithFavorite)],
      ['query'],
    ),
  'getDailyAffirmation' : IDL.Func([], [AffirmationWithFavorite], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(AffirmationWithFavorite)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
  'update' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'gratitude' : IDL.Null,
    'love' : IDL.Null,
    'mindfulness' : IDL.Null,
    'success' : IDL.Null,
    'confidence' : IDL.Null,
    'health' : IDL.Null,
  });
  const Time = IDL.Int;
  const Affirmation = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'isCustom' : IDL.Bool,
    'category' : Category,
    'authorPrincipal' : IDL.Principal,
  });
  const AffirmationWithFavorite = IDL.Record({
    'affirmation' : Affirmation,
    'isFavorite' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'create' : IDL.Func([IDL.Text, Category], [IDL.Nat], []),
    'delete' : IDL.Func([IDL.Nat], [], []),
    'getAllByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(AffirmationWithFavorite)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomAffirmations' : IDL.Func(
        [],
        [IDL.Vec(AffirmationWithFavorite)],
        ['query'],
      ),
    'getDailyAffirmation' : IDL.Func([], [AffirmationWithFavorite], ['query']),
    'getFavorites' : IDL.Func(
        [],
        [IDL.Vec(AffirmationWithFavorite)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
    'update' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };